config/routes.rb
Rails.application.routes.draw do
  # config/routes.rb
  get 'evaluation_results/comparison', to: 'evaluation_results#compare', as: 'evaluation_results_comparison'

  post '/admin/submit_excel_selection', to: 'dynamic_tables#submit_excel_selection', as: :admin_submit_excel_selection
  post 'handle_excel_actions',       to: 'dynamic_tables#handle_excel_actions', as: :handle_excel_actions   
  get  '/admin/upload_excel',        to: 'dynamic_tables#upload_excel',        as: :admin_upload_excel
  post '/admin/preview_excel',       to: 'dynamic_tables#preview_excel',       as: :admin_preview_excel
  post '/admin/submit_preview',      to: 'dynamic_tables#submit_preview',      as: :admin_submit_preview
  post '/admin/import_excel_tables', to: 'dynamic_tables#import_excel_tables', as: :admin_import_excel_tables
  post '/admin/create_main_tables',  to: 'dynamic_tables#create_main_tables',  as: :admin_create_main_tables
  post '/admin/create_child_tables', to: 'dynamic_tables#create_child_tables', as: :admin_create_child_tables
  post '/admin/create_features',     to: 'dynamic_tables#create_features',     as: :admin_create_features
  get  '/admin/test_tables',         to: 'dynamic_tables#test_tables',         as: :admin_test_tables
  namespace :admin do
    resources :submissions, only: [:index, :show]
  end

  # ✅ API namespace for suppliers
  namespace :api do
    get  '/subsystems/:subsystem_id/table_order',       to: 'dynamic_tables#table_order'
    get  '/subsystems/:subsystem_id/table_definitions', to: 'dynamic_tables#table_definitions'
    post '/subsystems/:subsystem_id/save_all',          to: 'dynamic_tables#save_all'
    get '/subsystems/:subsystem_id/submitted_data',     to: 'dynamic_tables#submitted_data'
    get 'my_submissions',                               to: 'dynamic_tables#my_submissions'
    
    namespace :supplier do
      resources :suppliers,      only: [:create, :index, :show]
      resources :projects,       only: [:index]
      resources :project_scopes, only: [:index]
      resources :systems,        only: [:index]
      resources :subsystems,     only: [:index]
      get  'subsystem_tables', to: 'suppliers#subsystem_tables'
      post 'register',         to: 'suppliers#register'
      post 'login',            to: 'sessions#create'
      get  'profile',          to: 'sessions#profile'
      get  'dashboard',        to: 'suppliers#dashboard'
      get  'supplier_data',    to: 'supplier_data#index'
    end

    # Nested routes for Projects → ProjectScopes → Systems → Subsystems
    resources :projects do
      resources :project_scopes do
        resources :systems do
          resources :subsystems, only: [] do
            post :submit_all,      on: :member
            get  :submitted_data,  on: :member
            put  :update_submission, on: :member
          end
        end
      end
    end

    resources :notifications, only: [:index, :update] do
      member do
        post :approve_supplier
        post :reject_supplier
      end
    end

    resources :sub_tables, only: [:index]

    # Additional dynamic‐table routes
    get   '/dynamic_tables/:table_name',     to: 'dynamic_tables#index'
    patch '/dynamic_tables/:table_name/:id', to: 'dynamic_tables#update'
    get   '/table_metadata/:table_name',     to: 'dynamic_tables#table_metadata'
    post  '/save_data/:table_name',          to: 'dynamic_tables#save_data'
  end

  # -------------------------
  # Non‐API (legacy) routes
  # -------------------------
  resources :projects do
    resources :project_scopes do
      resources :systems do
        resources :subsystems do
          post :submit_all, on: :member
          resources :fire_alarm_control_panels, only: [:create, :index]
        end
      end
    end
  end

  resources :comparisons, only: [:index] do
    collection do
      post :generate
      get  :export
    end
  end

  resources :suppliers do
    collection do
      get :search
      get 'dashboard', to: 'suppliers#dashboard'
    end
    member do
      post :set_membership_and_approve
    end
  end

  resources :notifications do
    member do
      get  :manage_membership
      post :approve_supplier
      post :reject_supplier
    end
  end

  resources :requirements_data, only: [:index] do
    collection do
      post :update
      get  :download
    end
  end

   resources :reports, only: [:index] do
    collection do
      get :evaluation_tech_report
      get :evaluation_data
      get :generate_evaluation_report
      get :evaluation_result
      get :recommendation

      get :generate_excel_report

      get :apple_to_apple_comparison
      get :show_comparison_report
      get :generate_comparison_report
      get :evaluation_result_comparison_form
      get :sow
      get :missing_items
      get :differences
      get :interfaces
    end
  end

  resources :evaluation_results, only: [:index] do
    collection do
      post :evaluate     # kicks off the service
      get  :download     # streams Excel
      get  :comparison
    end
  end

  resources :project_scopes, only: [:index, :show, :new, :create]
  resources :systems,        only: [:index, :show, :new, :create]
  resources :subsystems,     only: [:index, :show, :new, :create]

  get  'up',                           to: 'rails/health#show',           as: :rails_health_check
  get  'projects/download_excel',      to: 'projects#download_excel',      as: :download_excel
  get  'reports/generate_excel_report',to: 'reports#generate_excel_report',as: :generate_excel_report

  devise_for :users

  authenticated :user do
    root to: 'dashboard#index', as: :authenticated_root
  end
  devise_scope :user do
    root to: 'devise/sessions#new', as: :unauthenticated_root
  end

  # Admin panel routes
  get   '/admin',                           to: 'dynamic_tables#admin'
  post  '/admin/add_column',                to: 'dynamic_tables#add_column'
  post  '/admin/create_table',              to: 'dynamic_tables#create_table'
  post  '/admin/create_multiple_tables',    to: 'dynamic_tables#create_multiple_tables'
  post  '/admin/create_multiple_sub_tables',to: 'dynamic_tables#create_multiple_sub_tables'
  post  '/admin/create_multiple_features',  to: 'dynamic_tables#create_multiple_features'
  post  '/admin/move_table',                to: 'dynamic_tables#move_table',       as: :move_table_dynamic_tables
  get   '/admin/sub_tables',                to: 'dynamic_tables#sub_tables'
  get   '/admin/check_table_name',          to: 'dynamic_tables#check_table_name'
  get   '/dynamic_tables/:table_name/columns/:column_name/edit_metadata',
        to: 'dynamic_tables#edit_metadata',   as: :edit_metadata_dynamic_tables
  patch '/dynamic_tables/:table_name/columns/:column_name/update_metadata',
        to: 'dynamic_tables#update_metadata', as: :update_metadata_dynamic_tables
  get   '/dynamic_tables/:table_name',      to: 'dynamic_tables#show',           as: :dynamic_table
  get   '/subsystems/:subsystem_id/:table_name',
        to: 'dynamic_tables#show_with_subsystem',                      as: :subsystem_dynamic_table
end

app/models/Project.rb
class Project < ApplicationRecord
  # has_many :systems, dependent: :destroy
  has_many :project_scopes
  has_and_belongs_to_many :suppliers
#   has_one :fire_alarm_control_panel
# accepts_nested_attributes_for :fire_alarm_control_panel
end

app/controllers/api/supplier/projects_controller.rb
module Api
  module Supplier
    class ProjectsController < Api::ApplicationController
      def index
        projects = Project.all
        render json: projects
      end
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = Project.all.includes(:project_scopes) # Include associated project scopes for better query performance
  end

  def show
    @project = Project.find(params[:id])
    @project_scopes = @project.project_scopes.includes(:systems)
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to projects_path, notice: "Project created successfully."
    else
      render :new
    end
  end

  private

  def project_params
    params.require(:project).permit(:name)
  end
end

app/views/projects/_project_details.html.erb
<div class="overflow-x-auto">
  <div class="bg-white shadow rounded-lg p-6" data-controller="tabs">
    <h2 class="text-xl font-semibold text-gray-900">Projects</h2>
    <div class="my-4 flex justify-between items-center">
      <%= link_to "Add New Project", new_project_path, class: "bg-buttonRed text-white py-2 px-4 rounded ml-4" %>
    </div>
  </div>

  <table class="min-w-full divide-y divide-gray-200 border border-gray-200 rounded-full">
    <thead class="bg-tableHeaderBg">
      <tr>
        <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Project Name</th>
        <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Action</th>
      </tr>
    </thead>
    <tbody class="bg-white divide-y divide-gray-200">
      <% @projects.each do |project| %>
        <tr class="hover:bg-tableRowHoverBg">
          <!-- Project Name -->
          <td class="px-6 py-4 whitespace-nowrap">
            <div class="text-sm font-medium text-gray-900"><%= project.name %></div>
          </td>

          <td class="px-6 py-4">
    <%= link_to "View Scopes", project_project_scopes_path(project), class: "text-blue-500 hover:underline" %>
  </td>
  <td class="px-6 py-4">
    <%= link_to "View", project_path(project), class: "text-red-600 hover:text-red-900" %>
  </td>

          <!-- Actions -->
          <td class="px-6 py-4 whitespace-nowrap flex items-center space-x-4">
            <%= link_to project_path(project), class: "text-red-600 hover:text-red-900 flex items-center space-x-1" do %>
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="h-5 w-5">
                <path stroke-linecap="round" stroke-linejoin="round" d="M2.036 12.322a1.012 1.012 0 0 1 0-.639C3.423 7.51 7.36 4.5 12 4.5c4.638 0 8.573 3.007 9.963 7.178.07.207.07.431 0 .639C20.577 16.49 16.64 19.5 12 19.5c-4.638 0-8.573-3.007-9.963-7.178Z" />
                <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z" />
              </svg>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/projects/index.html.erb
<%= render "project_details", projects: @projects %>

app/views/projects/new.html.erb
<%= form_with model: @project, local: true do |form| %>
  <h1 class="text-xl font-semibold">Create New Project</h1>

  <div class="mb-4">
    <%= form.label :name, "Project Name" %>
    <%= form.text_field :name, class: "form-input w-full" %>
  </div>


  <div class="mt-4">
    <%= form.submit "Create Project", class: "bg-blue-500 hover:bg-blue-600 text-white py-2 px-4 rounded" %>
  </div>
<% end %>

app/views/projects/show.html.erb
<h1 class="text-xl font-bold">Project: <%= @project.name %></h1>

<h2 class="text-lg font-semibold mt-6">Project Scopes</h2>
<ul>
  <% @project.project_scopes.each do |project_scope| %>
    <li>
      <%= link_to project_scope.name, project_project_scope_path(@project, project_scope), class: "text-blue-500 hover:underline" %>
    </li>
  <% end %>
</ul>

<h2 class="text-lg font-semibold mt-6">Systems</h2>
<div>
  <% @project.project_scopes.each do |project_scope| %>
    <% project_scope.systems.each do |system| %>
      <div class="mb-4">
        <h3 class="text-md font-semibold"><%= system.name %></h3>
        <%= link_to "View #{system.name}", project_project_scope_system_path(@project, project_scope, system), class: "bg-blue-500 text-white py-2 px-4 rounded" %>
      </div>
    <% end %>
  <% end %>
</div>